name: Build macOS AmigaLive

# Trigger workflow on push to main branch or manual trigger
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Step 3: Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Step 4: Install dependencies
      - name: Install npm dependencies and Tauri CLI
        run: |
          npm install
          npm install -g @tauri-apps/cli
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . "$HOME/.cargo/env"

      # Step 5: Build the app
      - name: Build Tauri app (macOS)
        run: npm run tauri build

      # Step 6: Upload built artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: AmigaLive-macOS
          path: src-tauri/target/release/bundle/macos/*
