name: Build AmigaLive Cross-Platform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: universal-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # ---- Linux dependencies ----
      - name: Install dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev libayatana-appindicator3-dev \
            libsoup-3.0-dev webkit2gtk-4.1 libwebkit2gtk-4.1-dev \
            patchelf pkg-config curl file

      # ---- Fix AppImage bundler permissions ----
      - name: Fix AppImage permissions (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p ~/.cache/tauri
          chmod +x ~/.cache/tauri || true
          echo "Ensuring AppImage tools will be executable"

      - name: Install frontend dependencies
        run: npm install

      - name: Build Tauri app
        env:
          TAURI_BUNDLE_APPIMAGE: "true"
        run: npm run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AmigaLive-${{ matrix.target }}
          path: |
            src-tauri/target/release/bundle/**/*
